using DevExpress.Drawing;
using DevExpress.XtraRichEdit;
using DevExpress.XtraRichEdit.API.Native;
using System.Drawing;
using System.Runtime.InteropServices;

internal static class Program {
    public static int Main(string[] args) {
        try {
            // Use the Skia Drawing Engine
            Settings.DrawingEngine = DrawingEngine.Skia;

            string fileName = Path.Combine(AppContext.BaseDirectory, "fontTest.docx");

            // Include Fonts in the Application
            string[] fonts = ["Inter-Regular.ttf", "NotoSans-Regular.ttf"];
            string[] fontFiles = [.. fonts.Select(f => Path.Combine(AppContext.BaseDirectory, f))];

            // Register fonts before loading documents
            foreach (var fp in fontFiles) {
                DXFontRepository.Instance.AddFont(fp);
            }
            using (var wordProcessor = new RichEditDocumentServer())
            {
                Document doc = wordProcessor.Document;
                doc.AppendText("This document is generated by Word Processing Document API: Inter font\r\n");
                CharacterProperties cp =
                    doc.BeginUpdateCharacters(doc.Paragraphs[0].Range);
                cp.FontName = "Inter";
                doc.EndUpdateCharacters(cp);
                doc.AppendText("This document is generated by Word Processing Document API: NotoSans font");
                CharacterProperties cp1 =
                    doc.BeginUpdateCharacters(doc.Paragraphs[1].Range);
                cp1.FontName = "Noto Sans";
                doc.EndUpdateCharacters(cp1);

                wordProcessor.SaveDocument(fileName, DocumentFormat.Docx);

                using var exportedPdf = new MemoryStream();
                wordProcessor.ExportToPdf(exportedPdf);
                exportedPdf.Position = 0;
                using var ouput = Console.OpenStandardOutput();
                exportedPdf.CopyTo(ouput);
                ouput.Flush();

                Log("Done.");
                return 0;
            }
        }
        catch (Exception e) {
            Log("ERROR:");
            Log(e.ToString());
            return 1;
        }
    }

    private static void Log(string message) =>
        Console.Error.WriteLine($"[{DateTimeOffset.UtcNow:O}] {message}");
}